# pytorch_lightning==2.0.0
trainer:
  accelerator: 'gpu'
model:
  in_channels_layers:
    - [64, 96, 192]
    - [108, 152, 144]
  fused_channels_layers:
    - [216, 304, 288]
    - [-1, 368, 480]
  out_channels_layers:
    - [108, 152, 144]
    - [108, 184, 240]
  depths_layers:
    - [3, 3, 3]
    - [2, 3, 3]
  mlp_ratio_layers:
    - [4, 4, 4]
    - [2, 2, 2]
  transformer_norm_type: 'LN'
  mlp_drop_rate: 0.1
  mlp_act_type: 'GELU'
  attn_proj_act_type: 'ReLU'
  attn_norm_type: 'LN'
  drop_path_rate: 0.1
  avg_pool_outputs: [2, 4, 6]
  num_joints: 21
  num_classes: 0