model:
  in_channels: 3
  embedding_ch: 64
  out_indices: [0, 1, 2, 3]
  depths: [3, 4, 5, 6]
  groups: [3, 3, 6, 3]
  post_norm: True
  dropout_params:
    drop_rate: 0.2
    drop_path: 0.2
    drop: 0.2
    mlp_ratio: 1.0
    layer_scale: 1.2

data:
  data_dir: "data/temp"
  batch_size: 100
  get_data_func: configure_mnist_dataset
  train_ratio: 0.75
  transform: MnistTransform

optimizer: AdamW
