# pytorch_lightning==2.0.0
trainer:
  accelerator: gpu
model:
  in_channels: 3
  out_indices: [ 1, 2, 3 ]
  depths: [ 3, 3, 10, 2 ]
  widths: [ 32, 64, 96, 192 ]
  stem_act_type: 'GELU'
  stem_norm_type: 'BN'
  moga_ratio: [ 1, 3, 4 ]
  moga_dilations: [ 1, 2, 3 ]
  drop_path_rate: 0.1
  drop_rate: 0.1
  ffn_scales: [ 8, 8, 4, 4 ]
  ffn_act_type: 'GELU'
  fd_act_type: 'GELU'
  moga_act_type: 'SiLU'