# pytorch_lightning==2.0.0
seed_everything: true
trainer:
  accelerator: gpu
  strategy: auto
  devices: 1
  max_epochs: 2
  profiler:
    class_path: lightning.pytorch.profilers.AdvancedProfiler
    init_args:
      dirpath: "data/logs"
      filename: "perf_logs"
  callbacks:

data:
  data_dir: "data/temp"
  batch_size: 16
  num_workers: 6
  get_data_func:
    class_path: feature_extractor.MNIST_dataset_configure
  train_ratio: 0.75
  transform:
    class_path: feature_extractor.MNISTransform
    init_args:
      size: 256
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5e-5
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 200
ckpt_path: "data/models/backbone_mnist.ckpt"